server:
  port: 9093

spring:
  application:
    name: consumer-feign

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-8761.com:8761/eureka/
  instance:
    preferIpAddress: true

## 扩展 IPing 实现
producer:
  ribbon:
    NFLoadBalancerPingClassName: com.javachen.ping.MyPing