server:
  port: 8761

spring:
  application:
    name: spring-cloud-eureka-server
  cloud:
    inetutils:
      ignoredInterfaces:  #禁用网卡
        - docker0
        - veth.*
        - en0
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    #ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5 #每隔5秒剔除一次失效的服务，默认30秒
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期，默认90秒
    enable-self-preservation: false #关闭自我保护

---
spring:
  profiles: eureka-server1

server:
  port: 8761

eureka:
  instance:
    hostname: eureka-8761.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-8762.com:8762/eureka/,http://eureka-8763.com:8763/eureka/

---
spring:
  profiles: eureka-server2

server:
  port: 8762

eureka:
  instance:
    hostname: eureka-8762.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-8761.com:8761/eureka/,http://eureka-8763.com:8763/eureka/

---
spring:
  profiles: eureka-server3

server:
  port: 8763

eureka:
  instance:
    hostname: eureka-8763.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-8761.com:8761/eureka/,http://eureka-8762.com:8762/eureka/
