server:
  port: 8000

spring:
  application:
    name: spring-cloud-oauth2-resource

#security:
#  oauth2:
#    resource:
#      user-info-uri: http://localhost:9999/user/info
#      token-info-uri: http://localhost:9999/oauth/check_token
#      client-id: web
#      client-secret: secret

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth: DEBUG