spring:
  application:
    name: spring-cloud-consul
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        health-check-interval: 20s
        instanceId: ${spring.application.name}:${server.port}

server:
  port: 8000