server:
  port: 8080

security:
  basic:
    enabled: false
  oauth2:
    resource:
      tokenInfoUri: http://localhost:9999/oauth/check_token
      userInfoUri: http://localhost:8000/user/me
    client:
      accessTokenUri: http://localhost:9999/oauth/token
      userAuthorizationUri: http://localhost:9999/oauth/authorize
      clientId: web
      clientSecret: secret
      scope: read,write,trust
