spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/tmp/test
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
  h2:
    console:
      enabled: true
      path: /h2

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'