server:
  port: 3344

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:javachen/spring-cloud-config.git #GitHub上面的git仓库名字
  security:
    user:
      name: admin
      password: 123456
      roles: SYSTEM


eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://admin:654321@localhost:8761/eureka/
  instance:
    preferIpAddress: true