server:
  port: 9526
spring:
  cloud:
    gateway:
      routes:
        - id: baidu_route
          uri: http://www.baidu.com
          predicates:
            - Path=/baidu
        - id: sina_route
            uri: http://www.sina.com
            predicates:
              - Path=/sina