server:
  port: 8000

spring:
  application:
    name: spring-cloud-oauth2-resource

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9999/oauth/check_token
    client:
      accessTokenUri: http://localhost:9999/oauth/token
      userAuthorizationUri: http://localhost:9999/oauth/authorize
      client-id: web
      client-secret: secret
      scope: read,write,trust

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth: DEBUG