server:
  port: 8000

spring:
  security:
    basic: false
security:
  oauth2:
    resource:
      tokenInfoUri: http://localhost:8080/oauth/check_token
#      userInfoUri: http://localhost:9999/user/me
    client:
      clientId: client
      clientSecret: secret
      scope: any
      accessTokenUri: http://localhost:8080/oauth/token
      userAuthorizationUri: http://localhost:8080/oauth/authorize
      clientAuthenticationScheme: form
