server:
  port: 9999

spring:
  application:
    name: spring-cloud-oauth2-service

  redis:
    host: 192.168.1.111
    password: 123456
    port: 6379


logging:
  level:
    org.springframework.security: DEBUG
