server:
  port: 8080

spring:
  application:
    name: provider
  jpa:
    # 让hibernate打印执行的SQL
    show-sql: true

logging:
  level:
    root: INFO
    # 配置日志级别，让hibernate打印出执行的SQL参数
    org.hibernate: INFO

management:
  endpoints:
    web:
      exposure:
        # 开放所有监控端点
        include: '*'
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: always
