server:
  port: 9000

spring:
  application:
    name: consumer-hystrix


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 6000 # 设置hystrix的超时时间为6000ms