spring:
  application:
    name: provider

server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true #当你获取host时，返回的不是主机名，而是ip
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        # 开放所有监控端点
        include: '*'
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: always


info:
  app.name: spring-cloud-provider
  company.name: www.javachen.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$